<?php if (isset($this->controller) && $this->controller): ?>
    <h2>Controller</h2>
    <p>
        <?= $this->escapeHtml($this->controller) ?>
        <?php if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller): ?>
            <?= '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')' ?>
        <?php endif; ?>
    </p>
<?php endif ?>
