<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
        <h2>Additional information</h2>
        <h3><?= get_class($this->exception) ?></h3>
        <dl>
            <dt>File:</dt>
            <dd>
                <pre><?= $this->exception->getFile() ?>:<?= $this->exception->getLine() ?></pre>
            </dd>
            <dt>Message:</dt>
            <dd>
                <pre><?= $this->exception->getMessage() ?></pre>
            </dd>
            <dt>Stack trace:</dt>
            <dd>
                <pre><?= $this->exception->getTraceAsString() ?></pre>
            </dd>
        </dl>

        <?php $exception = $this->exception->getPrevious() ?>
        <?php if ($exception): ?>
            <h2>Previous exceptions</h2>
            <ul class="unstyled">
                <?php while($exception): ?>
                    <li>
                        <h3><?= get_class($exception); ?></h3>
                        <dl>
                            <dt>File:</dt>
                            <dd>
                                <pre><?= $exception->getFile() ?>:<?= $exception->getLine() ?></pre>
                            </dd>
                            <dt>Message:</dt>
                            <dd>
                                <pre><?= $exception->getMessage() ?></pre>
                            </dd>
                            <dt>Stack trace:</dt>
                            <dd>
                                <pre><?= $exception->getTraceAsString() ?></pre>
                            </dd>
                        </dl>
                    </li>
                    <?php $exception = $exception->getPrevious() ?>
                <?php endwhile; ?>
            </ul>
        <?php endif; ?>
    <?php else: ?>
        <h3><?php echo $this->translate('No Exception available') ?></h3>
    <?php endif ?>
<?php endif ?>
