<div class="jumbotron">
    <h1>PRX Skeleton Application</h1>
    <p>
        You have installed <a href="https://github.com/grizzm0/PrxSkeletonApplication">PRX Skeleton Application</a>.
        This skeleton comes with a few pre-installed modules to ease up the creation of new projects using <a href="http://www.doctrine-project.org/">DoctrineORM</a>, <a href="http://jquery.com/">jQuery</a>, <a href="https://code.google.com/p/html5shiv/">html5shiv</a> and <a href="http://getbootstrap.com/">Twitter Bootstrap</a>.
    </p>
    <p>
        Twitter Bootstrap is compiled from <a href="http://lesscss.org/">less</a> using <a href="https://github.com/leafo/lessphp">lessphp</a> for easy customization and variable manipulation.
        The output should be cached in production using <a href="https://github.com/grizzm0/PrxSkeletonApplication/blob/master/config/autoload/assetmanager.local.php.dist">assetmanager.local.php.dist</a>.
    </p>
    <p>
        You are currently running Zend Framework <?= \Zend\Version\Version::VERSION ?>.
    </p>
    <p><a class="btn btn-primary btn-lg" href="https://github.com/zendframework/zf2" role="button">Fork Zend Framework 2 on GitHub</a></p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Development</h3>
            </div>
            <div class="panel-body">
                <p>
                    Never commit your *.local.php files to VCS.
                </p>
                <h3>Copy files</h3>
                <pre>cp ./config/autoload/development.local.php.dist ./config/autoload/development.local.php
cp ./config/autoload/doctrine.local.php.dist ./config/autoload/doctrine.local.php</pre>
                <h3>Edit files</h3>
                <p>
                    Edit doctrine.local.php with your database settings
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Deployment for production</h3>
            </div>
            <div class="panel-body">
                <p>
                    Never commit your *.local.php files to VCS.
                </p>
                <h3>Copy files</h3>
                <pre>cp ./config/autoload/assetmanager.local.php.dist ./config/autoload/assetmanager.local.php
cp ./config/autoload/doctrine.local.php.dist ./config/autoload/doctrine.local.php</pre>
                <h3>Edit files</h3>
                <p>
                    Edit doctrine.local.php with your database settings.<br>
                    Uncomment config_cache_enabled, cache_dir and module_map_cache_enabled in <a href="https://github.com/grizzm0/PrxSkeletonApplication/blob/master/config/application.config.php#L19-L21">./config/application.config.php</a>.<br>
                    Comment development settings in <a href="https://github.com/grizzm0/PrxSkeletonApplication/blob/master/public/index.php#L3-L5">index.php</a>.
                </p>
            </div>
        </div>
    </div>
</div>
