<div class="jumbotron">
    <h1>ZF2 Skeleton Application</h1>
    <p>
        You have installed <a href="https://github.com/svycka/zf2-skeleton-application">ZF2 Skeleton Application</a>.
        This skeleton comes with a few pre-installed modules to ease up the creation of new projects using <a href="http://jquery.com/">jQuery</a> and <a href="http://getbootstrap.com/">Twitter Bootstrap</a>.
    </p>
    <p>
        Twitter Bootstrap is compiled from <a href="http://lesscss.org/">less</a> using <a href="https://github.com/oyejorge/less.php">less.php</a> for easy customization and variable manipulation.
        The output should be cached in production using <a href="https://github.com/svycka/zf2-skeleton-application/blob/master/config/autoload/assetmanager.local.php.dist">assetmanager.local.php.dist</a>.
    </p>
    <p>
        You are currently running Zend Framework <?= \Zend\Version\Version::VERSION ?>.
    </p>
    <p><a class="btn btn-primary btn-lg" href="https://github.com/zendframework/zf2" role="button">Fork Zend Framework 2 on GitHub</a></p>
</div>
