<?= $this->doctype().PHP_EOL ?>
<html lang="en">
<head>
    <?= $this->headTitle('PRX Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->setSeparator(PHP_EOL)
        ->setCharset('utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink()->setSeparator(PHP_EOL)
        ->prependStylesheet($this->basePath() .'/asset/css/application.css')
        ->prependStylesheet($this->basePath() .'/asset/css/bootstrap.css') ?>

    <?= $this->headScript()->setSeparator(PHP_EOL)
        ->prependFile($this->basePath() .'/asset/js/bootstrap.js')
        ->prependFile($this->basePath() .'/asset/js/jquery.js')
        ->prependFile($this->basePath() .'/asset/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>

</head>
<body>
    <header id="navbar" class="navbar navbar-default navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <a href="<?= $this->url('home') ?>" class="navbar-brand">PRX</a>
            </div>
            <nav class="navbar-collapse" role="navigation">
                <?= $this->navigationMenu()->renderMenu('navigation', array('ulclass' => 'nav navbar-nav')).PHP_EOL ?>
            </nav>
        </div>
    </header>

    <main id="content" class="container" role="main">
        <?= $this->content.PHP_EOL ?>
    </main>

    <footer id="footer" class="container">
        &copy; <?= date('Y') ?> - <a href="https://github.com/grizzm0">grizzm0</a>
    </footer>
    <?= $this->inlineScript()->setSeparator(PHP_EOL) ?>

</body>
</html>
