<?= $this->doctype().PHP_EOL ?>
<html lang="en">
<head>
    <?= $this->headTitle('ZF2 Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->setSeparator(PHP_EOL)
        ->setCharset('utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink()->setSeparator(PHP_EOL)
        ->prependStylesheet($this->basePath() .'/asset/css/application.css') ?>

    <?= $this->headScript()->setSeparator(PHP_EOL)
        ->prependFile($this->basePath() .'/asset/js/application.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js') ?>

</head>
<body>
    <header id="navbar" class="navbar navbar-default navbar-fixed-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="<?= $this->url('home') ?>" class="navbar-brand">ZF2</a>
            </div>
            <nav class="collapse navbar-collapse" role="navigation">
                <?= $this->navigationMenu()->renderMenu('navigation', array('ulclass' => 'nav navbar-nav')).PHP_EOL ?>
            </nav>
        </div>
    </header>

    <main id="content" class="container" role="main">
        <?= $this->content.PHP_EOL ?>
    </main>

    <footer id="footer" class="container">
        &copy; <?= date('Y') ?> - <a href="https://github.com/svycka">svycka</a>
    </footer>
    <?= $this->inlineScript()->setSeparator(PHP_EOL) ?>
</body>
</html>

