<?= $this->doctype().PHP_EOL ?>
<html lang="en">
<head>
    <?= $this->headTitle('PRX Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->setSeparator(PHP_EOL)
        ->setCharset('utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <?= $this->headLink()->setSeparator(PHP_EOL)
        ->prependStylesheet($this->basePath() .'/asset/css/application.css')
        ->prependStylesheet($this->basePath() .'/asset/css/bootstrap.css') ?>

    <?= $this->headScript()->setSeparator(PHP_EOL)
        ->prependFile($this->basePath() .'/asset/js/bootstrap.js')
        ->prependFile($this->basePath() .'/asset/js/jquery.js')
        ->prependFile($this->basePath() .'/asset/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9')) ?>

</head>
<body>
    <main id="content" class="container" role="main">
        <?= $this->content.PHP_EOL ?>
    </main>
    <?= $this->inlineScript()->setSeparator(PHP_EOL) ?>
</body>
</html>
